name: smart_hub
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # BLE packages
  flutter_reactive_ble: ^5.3.1
  permission_handler: ^11.3.1

  #Alerts
  fluttertoast: ^8.2.8
  rflutter_alert: ^2.0.7


  # UI packages
  cupertino_icons: ^1.0.2
  animations: ^2.0.11
  skeleton_text: ^3.0.1
  animated_text_kit: ^4.2.2
  loading_animation_widget: ^1.2.0+4
  vibration: ^1.9.0

  #Mobile Settings
  app_settings: ^5.1.1

  #Local Storage
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
